server:
  port: 8083
spring:
  mongodb:
    uri: ${URI}
    
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}

rabbitmq:
  exchange:
    name: ${RABBIT_NAME}
  queue:
    name: ${RABBIT_QUEUE}
  routing:
    key: ${RABBIT_ROUTING}

gemini:
  api:
    url: ${GEMINI_URL}
    key: ${GEMINI_KEY}