spring:
  mongodb:
      uri: ${URI}
  rabbitmq:
    host: localhost
    port: ${RABBIT_PORT}
    username: ${USERNAME}
    password: ${PASSWORD}

server:
    port: 8082
services:
  user-service:
    url: ${USER_SERVICE_URL}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}

rabbitmq:
  exchange:
    name: ${RABBIT_NAME}
  queue:
      name: ${RABBIT_QUEUE}
  routing:
      key: ${RABBIT_ROUTING}